-
  branches:
    only:
    - nuget

  image: Visual Studio 2017

  before_script: cd JDI.Light
  
  before_build:
  - nuget restore JDI.Light/JDI.Light.sln
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/set-screenresolution.ps1'))
  - ps: Set-ScreenResolution 1280 1024

  build_script:
    - msbuild JDI.Light/JDI.Light.sln /p:Configuration=Release /t:Rebuild

  test_script:
  - ps: .\JDI.Light\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntargetcode -register:user -target:"nunit3-console.exe" "-targetargs:""JDI.Light\JDI.Light.Tests\bin\Release\JDI.Light.Tests.dll""" -filter:"+[JDI.Light*]* -[JDI.Light.Tests*]*" -output:opencoverCoverage.xml

  after_build:
    - nuget pack "JDI.Light/JDI.Light/JDI.Light.csproj" -Prop Configuration=Release

  artifacts:
    - path: '*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server:
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg

  on_finish:
  - ps: .\Coverage.ps1

-
  branches:
    except:
    - nuget

  image: Visual Studio 2017

  before_build:
  - nuget restore JDI.Light/JDI.Light.sln
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/set-screenresolution.ps1'))
  - ps: Set-ScreenResolution 1280 1024

  build_script:
    - msbuild JDI.Light/JDI.Light.sln /p:Configuration=Release /t:Rebuild

  test_script:
  - ps: .\JDI.Light\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntargetcode -register:user -target:"nunit3-console.exe" "-targetargs:""JDI.Light\JDI.Light.Tests\bin\Release\JDI.Light.Tests.dll""" -filter:"+[JDI.Light*]* -[JDI.Light.Tests*]*" -output:opencoverCoverage.xml

  on_finish:
  - ps: .\Coverage.ps1